version: '3.8'
services:
  frontend:
    image: frontendlocmns
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
